services:
  # --- SERVICIO 1: Motor de Base de Datos (MySQL) ---
  database1:
    # Utiliza la imagen oficial de MySQL versión 8.0.
    image: mysql:8.0
    # Carga de variables de entorno desde un archivo externo para evitar exponer credenciales.
    env_file:
      - ./backend/.env
    environment:
      # Configuración de parámetros iniciales del motor mediante variables de entorno.
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      # Mapeo de puertos: el puerto 3308 del host se vincula al 3306 interno del contenedor.
      - "3308:3306"
    volumes:
      # Persistencia de datos: vincula un volumen lógico al directorio de datos de MySQL.
      - db_data:/var/lib/mysql

  # --- SERVICIO 2: Capa de Aplicación (Backend) ---
  backend:
    # Proceso de construcción basado en el Dockerfile ubicado en el directorio ./backend.
    build: ./backend
    volumes:
      # Montaje del archivo de configuración .env para sincronización en tiempo de ejecución.
      - ./backend/.env:/app/.env
    env_file:
      - ./backend/.env
    ports:
      # Exposición de la interfaz de programación de aplicaciones (API) en el puerto 3000.
      - "3000:3000"
    environment:
      # Configuración de conectividad: se utiliza el nombre del servicio 'database1' como hostname.
      - DB_HOST=database1
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=clinica
      - JWT_SECRET=clave
    depends_on:
      # Condicional de inicio: asegura que el servicio de base de datos esté operativo antes que el backend.
      - database1

  # --- SERVICIO 3: Interfaz de Usuario (Frontend) ---
  frontend:
    # Proceso de construcción basado en el Dockerfile ubicado en el directorio ./frontend.
    build: ./frontend
    ports:
      # Mapeo del puerto 80 (Nginx interno) al puerto 4200 del host para acceso web.
      - "4200:80"
    depends_on:
      # Condicional de inicio: el servicio depende de la disponibilidad de la API backend.
      - backend

# --- SECCIÓN DE VOLÚMENES ---
# Define estructuras de almacenamiento persistente para mitigar la volatilidad de los contenedores.
# El volumen 'db_data' permite preservar la integridad de la información ante reinicios o eliminaciones.
volumes:
  db_data: