# 1. Imagen base
FROM node:22-alpine

# 2. Directorio de trabajo
WORKDIR /app

# 3. Gestión de dependencias (Optimización de caché)
COPY package*.json ./
RUN npm install

# 4. Copiado del código fuente
COPY . .

# 5. Configuración de salida
EXPOSE 3000
CMD ["node", "server.js"]