# 1. Imagen base
# Se utiliza Node.js versión 22 sobre una distribución Alpine Linux.
# Alpine es elegida por su ligereza, reduciendo el tamaño de la imagen y la superficie de ataque.
FROM node:22-alpine

# 2. Directorio de trabajo
# Define el espacio de nombres dentro del contenedor donde se alojará la aplicación.
# Todas las instrucciones siguientes se ejecutarán en esta ruta.
WORKDIR /app

# 3. Gestión de dependencias (Optimización de caché)
# Se copian los archivos de definición de dependencias (package.json y package-lock.json).
# Instalar las dependencias en este paso permite a Docker cachear la capa de módulos;
# esto acelera las reconstrucciones si no hay cambios en las librerías.
COPY package*.json ./
RUN npm install

# 4. Copiado del código fuente
# Una vez instaladas las dependencias, se transfieren los archivos del proyecto al contenedor.
# Esto incluye la lógica de negocio, controladores y modelos.
COPY . .

# 5. Configuración de salida
# Indica que el contenedor escuchará peticiones en el puerto 3000.
EXPOSE 3000

# Ejecuta el proceso principal de la aplicación mediante Node.js.
# Se utiliza la forma de array (exec form) para una gestión correcta de señales del sistema.
CMD ["node", "server.js"]